import re
from argparse import Namespace
from dataclasses import dataclass
from typing import TYPE_CHECKING

from miles.utils.lora import is_lora_enabled
from miles.utils.run_uuid import RUN_UUID_LENGTH

if TYPE_CHECKING:
    from miles.utils.types import Sample

_NUM_TRAINED_ROLLOUTS_DIGITS = 8
_SERIALIZED_PATTERN = re.compile(
    rf"(?P<run_uuid>[0-9a-f]{{{RUN_UUID_LENGTH}}})-(?P<num_trained_rollouts>[0-9]{{{_NUM_TRAINED_ROLLOUTS_DIGITS}}})"
)


@dataclass(frozen=True)
class WeightVersion:
    run_uuid: str
    num_trained_rollouts: int

    def serialize(self) -> str:
        result = f"{self.run_uuid}-{self.num_trained_rollouts:0{_NUM_TRAINED_ROLLOUTS_DIGITS}d}"
        assert WeightVersion.deserialize(result) == self
        return result

    @staticmethod
    def deserialize(value: str) -> "WeightVersion":
        match = _SERIALIZED_PATTERN.fullmatch(str(value))
        if match is None:
            raise ValueError(
                f"invalid weight version {value!r}; "
                f"expected '<{RUN_UUID_LENGTH}-hex-run-uuid>-<{_NUM_TRAINED_ROLLOUTS_DIGITS}-digit-trained-rollout-count>'"
            )
        return WeightVersion(
            run_uuid=match.group("run_uuid"), num_trained_rollouts=int(match.group("num_trained_rollouts"))
        )


def try_parse_num_trained_rollouts(value: str) -> int | None:
    try:
        return WeightVersion.deserialize(value).num_trained_rollouts
    except ValueError:
        return None


def assert_samples_weight_version_sane(
    args: Namespace, samples: list["Sample"], rollout_id: int, *, is_eval: bool = False
) -> None:
    if args.debug_rollout_only or args.debug_skip_weight_update or is_lora_enabled(args):
        return

    if not any(sample.all_weight_version_spans for sample in samples):
        return

    current_run_uuid: str = args.run_uuid
    newest_rollout_id: int | None = None

    for sample in samples:
        versions = [span.version for span in sample.all_weight_version_spans]
        assert versions or sample.response_length == 0, (
            f"sample index={sample.index} has {sample.response_length} generated tokens but no weight version, "
            f"while other samples in this batch carry one"
        )

        parsed = [WeightVersion.deserialize(version) for version in versions]
        seen_current_run = False
        for item in parsed:
            if item.run_uuid == current_run_uuid:
                seen_current_run = True
                assert is_eval or item.rollout_id <= rollout_id, (
                    f"sample index={sample.index} carries weight version from rollout {item.rollout_id}, "
                    f"which is newer than the rollout {rollout_id} being generated"
                )
                newest_rollout_id = max(newest_rollout_id, item.rollout_id) if newest_rollout_id else item.rollout_id
            else:
                assert not seen_current_run, (
                    f"sample index={sample.index} has weight version run_uuid={item.run_uuid!r} after versions from "
                    f"the current run {current_run_uuid!r}; it was partially generated by an engine of another run"
                )

        if versions:
            assert seen_current_run, (
                f"sample index={sample.index} carries no weight version from the current run {current_run_uuid!r}; "
                f"it was generated by an engine belonging to another run"
            )

        if (max_staleness := args.max_weight_staleness) is not None and not is_eval:
            own_run = [item.rollout_id for item in parsed if item.run_uuid == current_run_uuid]
            if own_run:
                assert rollout_id - min(own_run) <= max_staleness, (
                    f"sample index={sample.index} was generated with weights from rollout {min(own_run)}, "
                    f"{rollout_id - min(own_run)} behind rollout {rollout_id} and past "
                    f"max_weight_staleness={max_staleness}"
                )

    if not is_eval and args.update_weights_interval == 1:
        allowed_lag = args.max_weight_staleness if args.max_weight_staleness is not None else 1
        assert newest_rollout_id is not None and newest_rollout_id >= rollout_id - allowed_lag, (
            f"the newest weights any sample in rollout {rollout_id} saw are from rollout {newest_rollout_id}, "
            f"more than {allowed_lag} behind; weight updates are not reaching the rollout engines"
        )
