import re
from argparse import Namespace
from dataclasses import dataclass
from typing import TYPE_CHECKING

from miles.utils.lora import is_lora_enabled
from miles.utils.run_uuid import RUN_UUID_LENGTH

if TYPE_CHECKING:
    from miles.utils.types import Sample

_NUM_TRAINED_ROLLOUTS_DIGITS = 8
_SERIALIZED_PATTERN = re.compile(
    rf"(?P<run_uuid>[0-9a-f]{{{RUN_UUID_LENGTH}}})-(?P<num_trained_rollouts>[0-9]{{{_NUM_TRAINED_ROLLOUTS_DIGITS}}})"
)


@dataclass(frozen=True)
class WeightVersion:
    run_uuid: str
    num_trained_rollouts: int

    def serialize(self) -> str:
        result = f"{self.run_uuid}-{self.num_trained_rollouts:0{_NUM_TRAINED_ROLLOUTS_DIGITS}d}"
        assert WeightVersion.deserialize(result) == self
        return result

    @staticmethod
    def deserialize(value: str) -> "WeightVersion":
        match = _SERIALIZED_PATTERN.fullmatch(str(value))
        if match is None:
            raise ValueError(
                f"invalid weight version {value!r}; "
                f"expected '<{RUN_UUID_LENGTH}-hex-run-uuid>-<{_NUM_TRAINED_ROLLOUTS_DIGITS}-digit-trained-rollout-count>'"
            )
        return WeightVersion(
            run_uuid=match.group("run_uuid"), num_trained_rollouts=int(match.group("num_trained_rollouts"))
        )


def try_parse_num_trained_rollouts(value: str) -> int | None:
    try:
        return WeightVersion.deserialize(value).num_trained_rollouts
    except ValueError:
        return None


def assert_samples_weight_version_sane(args: Namespace, samples: list["Sample"], rollout_id: int) -> None:
    if args.debug_rollout_only or args.debug_skip_weight_update or is_lora_enabled(args):
        return

    if not any(sample.all_weight_version_spans for sample in samples):
        return

    current_run_uuid: str = args.run_uuid
    newest_rollout_id: int | None = None
    oldest_per_sample: dict[int, int] = {}

    for sample in samples:
        versions = [span.version for span in sample.all_weight_version_spans]
        assert versions or sample.response_length == 0, (
            f"sample index={sample.index} has {sample.response_length} generated tokens but no weight version, "
            f"while other samples in this batch carry one"
        )

        parsed = [WeightVersion.deserialize(version) for version in versions]
        seen_current_run = False
        for item in parsed:
            if item.run_uuid == current_run_uuid:
                seen_current_run = True
                assert item.rollout_id <= rollout_id, (
                    f"sample index={sample.index} carries weight version from rollout {item.rollout_id}, "
                    f"which is newer than the rollout {rollout_id} being generated"
                )
                newest_rollout_id = (
                    item.rollout_id if newest_rollout_id is None else max(newest_rollout_id, item.rollout_id)
                )
            else:
                assert not seen_current_run, (
                    f"sample index={sample.index} has weight version run_uuid={item.run_uuid!r} after versions from "
                    f"the current run {current_run_uuid!r}; it was partially generated by an engine of another run"
                )

        if versions:
            assert seen_current_run, (
                f"sample index={sample.index} carries no weight version from the current run {current_run_uuid!r}; "
                f"it was generated by an engine belonging to another run"
            )

        if own_run := [item.rollout_id for item in parsed if item.run_uuid == current_run_uuid]:
            oldest_per_sample[sample.index] = min(own_run)

    # The bound is on how far behind the serving weights a sample is, and the
    # freshest version anyone in the batch saw is the best available stand-in
    # for what the engines were serving. rollout_id is not: under
    # update_weights_interval > 1 or a fully async backlog it legitimately runs
    # ahead of the engines, and measuring against it would reject valid runs.
    if (max_staleness := args.max_weight_staleness) is not None:
        for index, oldest in oldest_per_sample.items():
            assert newest_rollout_id - oldest <= max_staleness, (
                f"sample index={index} was generated with weights from rollout {oldest}, "
                f"{newest_rollout_id - oldest} behind the newest weights any sample in this batch saw "
                f"(rollout {newest_rollout_id}) and past max_weight_staleness={max_staleness}"
            )
